-- 1. Remova a FK ID_USUARIO da tabela TURMAS (se existir)
ALTER TABLE TURMAS DROP CONSTRAINT FK_TURMAS_USUARIO;
ALTER TABLE TURMAS DROP COLUMN ID_USUARIO;
GO

-- 2. Crie a tabela de associação USUARIO_TURMA
CREATE TABLE USUARIO_TURMA (
    ID_USUARIO INT NOT NULL,
    ID_TURMA INT NOT NULL,
    PRIMARY KEY (ID_USUARIO, ID_TURMA),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE,
    FOREIGN KEY (ID_TURMA) REFERENCES TURMAS(ID_TURMA) ON DELETE CASCADE
);
GO

