-- Criação do banco de dados
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'mydb')
    CREATE DATABASE mydb;
GO

USE mydb;
GO

-- Tabela USUARIO
CREATE TABLE USUARIO (
    ID_USUARIO INT IDENTITY(1,1) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    SENHA VARCHAR(255) NOT NULL,
    TIPO CHAR(1) NOT NULL
);
GO

-- Tabela TURMAS
CREATE TABLE TURMAS (
    ID_TURMA INT IDENTITY(1,1) PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    NOME VARCHAR(45) NOT NULL,
    DAT_CRIACAO DATETIME DEFAULT GETDATE(),
    IMG VARBINARY(MAX) NULL,
    CONSTRAINT FK_TURMAS_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIO(ID_USUARIO)
        ON DELETE CASCADE
);
GO

-- Tabela QUIZZES
CREATE TABLE QUIZZES (
    ID_QUIZZES INT IDENTITY(1,1) PRIMARY KEY,
    TITULO VARCHAR(45) NOT NULL,
    DAT_CRIACAO DATETIME DEFAULT GETDATE()
);
GO

-- Tabela DISCIPLINA
CREATE TABLE DISCIPLINA (
    ID_DISCIPLINA INT IDENTITY(1,1) PRIMARY KEY,
    ID_TURMA INT NOT NULL,
    ID_QUIZZES INT NOT NULL,
    DESCRICAO VARCHAR(45) NOT NULL,
    CONSTRAINT FK_DISCIPLINA_TURMAS FOREIGN KEY (ID_TURMA)
        REFERENCES TURMAS(ID_TURMA)
        ON DELETE CASCADE,
    CONSTRAINT FK_DISCIPLINA_QUIZZES FOREIGN KEY (ID_QUIZZES)
        REFERENCES QUIZZES(ID_QUIZZES)
        ON DELETE CASCADE
);
GO

-- Tabela PERGUNTAS
CREATE TABLE PERGUNTAS (
    ID_PERG INT IDENTITY(1,1) PRIMARY KEY,
    ID_QUIZ INT NOT NULL,
    ENUNCIADO TEXT NOT NULL,
    IMG VARCHAR(255) NULL,
    PONTOS DECIMAL(5,2) NOT NULL,
    TIPO CHAR(1) NOT NULL,
    CONSTRAINT FK_PERGUNTAS_QUIZZES FOREIGN KEY (ID_QUIZ)
        REFERENCES QUIZZES(ID_QUIZZES)
        ON DELETE CASCADE
);
GO

-- Tabela ALTERNATIVA
CREATE TABLE ALTERNATIVA (
    ID_ALT INT IDENTITY(1,1) PRIMARY KEY,
    ID_PERG INT NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    CORRETO BIT NOT NULL DEFAULT 0,
    CONSTRAINT FK_ALT_PERG FOREIGN KEY (ID_PERG)
        REFERENCES PERGUNTAS(ID_PERG)
        ON DELETE CASCADE
);
GO

-- Tabela RESPOSTAS
CREATE TABLE RESPOSTAS (
  ID_RESP INT IDENTITY(1,1) PRIMARY KEY,
  ID_ALT INT NOT NULL,
  ID_PERG INT NOT NULL,
  ID_USUARIO INT NOT NULL,
  TEXTO TEXT NULL,
  CONSTRAINT FK_RESP_USUARIO FOREIGN KEY (ID_USUARIO)
    REFERENCES USUARIO(ID_USUARIO)
    ON DELETE NO ACTION,
  CONSTRAINT FK_RESP_ALT FOREIGN KEY (ID_ALT)
    REFERENCES ALTERNATIVA(ID_ALT)
    ON DELETE CASCADE, -- Deixa um com CASCADE se necessário
  CONSTRAINT FK_RESP_PERG FOREIGN KEY (ID_PERG)
    REFERENCES PERGUNTAS(ID_PERG)
    ON DELETE NO ACTION
);
GO

-- Tabela NOTAS
CREATE TABLE NOTAS (
    ID_NOTA INT IDENTITY(1,1) PRIMARY KEY,
    ID_QUIZZES INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    VALOR DECIMAL(5,2) NOT NULL,
    DATA_NOTA DATETIME DEFAULT GETDATE(),
    CONSTRAINT FK_NOTAS_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIO(ID_USUARIO)
        ON DELETE CASCADE,
    CONSTRAINT FK_NOTAS_QUIZZES FOREIGN KEY (ID_QUIZZES)
        REFERENCES QUIZZES(ID_QUIZZES)
        ON DELETE CASCADE
);
GO
